# Generated by Django 4.1.7 on 2023-02-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('priority', models.SmallIntegerField(choices=[(1, 'high'), (2, 'medium'), (3, 'low')], default=3)),
                ('status', models.CharField(choices=[('c', 'completed'), ('w', 'waiting'), ('p', 'no progress')], default='p', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
